import { useEffect, useState } from 'react'
import { projects, type Project } from './data/projects'
import './App.css'

function App() {
  const [active, setActive] = useState(0)
  const [stage, setStage] = useState(0)

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) setActive(Number((entry.target as HTMLElement).dataset.project))
    }), { rootMargin: '-35% 0px -45% 0px' })
    document.querySelectorAll<HTMLElement>('[data-project]').forEach((element) => observer.observe(element))
    return () => observer.disconnect()
  }, [])

  return <main>
    <nav className="topbar"><a className="brand" href="#top">JYL / DA</a><div className="nav-links"><a href="#approach">Approach</a><a href="#work">Work</a><a href="#contact">Contact</a></div><span className="status"><i /> Available for analysis</span></nav>
    <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">01 / DATA ANALYST <span>2026 — PRESENT</span></p><h1>JUNG<br /><em>YE LIM</em></h1><p className="hero-line">Turning flows into<br /><strong>measurable data.</strong></p><p className="hero-ko">사용자의 행동과 업무 흐름을 이해하고,<br />데이터의 기준을 정의하고, 신뢰할 수 있는<br />분석 구조로 연결합니다.</p><div className="actions"><a className="text-link" href="#work">View analysis <span>↓</span></a><a className="text-link muted" href="https://github.com/siren8289" target="_blank" rel="noreferrer">GitHub <span>↗</span></a></div></div><div className="flow-visual">{['USER', 'EVENT', 'VALIDATE', 'MODEL', 'KPI', 'INSIGHT'].map((item, index) => <button className={`flow-node node-${index} ${index <= stage ? 'is-active' : ''}`} key={item} onMouseEnter={() => setStage(index)} onFocus={() => setStage(index)}><i />{item}{index < 5 && <b />}</button>)}<span className="flow-note">SOURCE / TRUST / DECISION</span></div><span className="scroll-mark">SCROLL TO EXPLORE <b>↓</b></span></section>
    <section className="approach shell" id="approach"><div><p className="eyebrow">02 / ANALYTICS APPROACH</p><h2>I ANALYZE THE FLOW,<br /><em>NOT JUST THE NUMBER.</em></h2></div><div className="approach-intro"><p>좋은 분석은 SQL에서 시작하지 않습니다.<br />먼저 무엇을 측정할지, 어떤 데이터가<br />신뢰 가능한지 정의합니다.</p><span>01 — 04 / METHOD</span></div><div className="stages">{[['DEFINE', 'Business question', 'Grain / Metric'], ['STRUCTURE', 'Event / Source', 'Dimension / Fact'], ['VALIDATE', 'Data quality', 'Reconciliation'], ['ANALYZE', 'KPI / Funnel', 'Segment / Insight']].map((item, index) => <button className={`stage ${index <= stage ? 'is-active' : ''}`} key={item[0]} onMouseEnter={() => setStage(index)}><span>0{index + 1}</span><strong>{item[0]}</strong><small>{item[1]}<br />{item[2]}</small></button>)}</div></section>
    <section className="work shell" id="work"><div className="work-header"><div><p className="eyebrow">03 / SELECTED WORK</p><h2>STRUCTURES<br /><em>THAT HOLD UP.</em></h2></div><p>Six studies in measurement,<br />validation, and analytical context.</p></div><div className="work-layout"><aside className="project-index">{projects.map((item, index) => <button className={index === active ? 'is-active' : ''} key={item.number} onClick={() => { setActive(index); document.getElementById(`project-${index}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }) }}><span>{item.number}</span>{item.title}</button>)}</aside><div>{projects.map((project, index) => <Project project={project} key={project.number} active={index === active} dataProject={index} />)}</div></div><p className="demo-note">ALL METRICS SHOWN ARE PROJECT STRUCTURE OR REPRODUCIBLE SAMPLE EVIDENCE — NOT CLAIMS OF BUSINESS OUTCOME.</p></section>
    <section className="experience shell"><div><p className="eyebrow">04 / EXPERIENCE</p><h2>FROM BUSINESS FLOW<br /><em>TO DATA STRUCTURE.</em></h2></div><div className="experience-grid"><div><p className="role-date">2026.03 — 2026.06</p><h3>Logos System</h3><p className="role-title">Technical Planning / Junior Researcher</p></div><div><p className="experience-copy">실무에서는 숫자를 분석하기 전, 그 숫자가 만들어지는 업무 규칙과 데이터 항목을 먼저 정리했습니다.</p><div className="rule-flow">BUSINESS RULE <b>→</b> DATA FIELD <b>→</b> STATE <b>→</b> VALIDATION <b>→</b> SYSTEM FLOW</div></div><ul><li>투자 자산관리 시스템 재구축과 FFMS / RISK / BRIEF 도메인 참여</li><li>메뉴·기능·화면 명세 약 1,245행 구조화 및 운영 문서 대조</li><li>투자 지시 관리 QA/QC 테스트 케이스 1,041건 작성</li><li>라우팅 문제, IA GAP 10건, 예외 흐름과 승인 조건 식별</li></ul></div></section>
    <section className="toolbox shell"><div><p className="eyebrow">05 / SKILLS / TOOLBOX</p><h2>A WORKING<br /><em>VOCABULARY.</em></h2></div><div className="tool-lines"><ToolLine title="ANALYSIS" text="Python · SQL · Pandas · Data Quality · KPI Definition · Funnel Analysis · Segmentation · Reconciliation" /><ToolLine title="DATABASE / DATA" text="PostgreSQL · MySQL · MariaDB · RDBMS · Star Schema · Dimension / Fact · Materialized View · Incremental Processing" /><ToolLine title="TECHNICAL FOUNDATION" text="Java · Spring · REST API · Airflow · PySpark · Git / GitHub" /><ToolLine title="WORKFLOW" text="Figma · Jira · Confluence · Cursor · Claude · AI-assisted development" /></div></section>
    <section className="education shell"><div><p className="eyebrow">06 / EDUCATION + AWARDS</p><h2>THE CONTEXT<br /><em>BEHIND THE WORK.</em></h2></div><div className="education-detail"><p><strong>Hanyang Women’s University</strong><br />Software Convergence</p><p><strong>Academic Credit Bank System</strong><br />Business Administration</p><div className="awards"><span className="label">AWARDS / PARTICIPATION</span><p>HUSS Regulation Innovation Competition — Excellence Award</p><p>Regional Innovation Talent Development Competition</p><p>Startup Idea Competition · ESG Idea Competition · Capstone Vlog Competition</p></div></div></section>
    <footer className="contact shell" id="contact"><p className="eyebrow">07 / CONTACT</p><h2>DATA IS NOT<br />JUST A NUMBER.<br /><em>IT IS THE RESULT<br />OF A FLOW.</em></h2><div className="contact-row"><div><p className="contact-name">JUNG YE LIM</p><p>Data Analyst</p></div><div className="contact-actions"><a className="text-link" href="https://github.com/siren8289" target="_blank" rel="noreferrer">View GitHub <span>↗</span></a><a className="text-link" href="mailto:hello@siren8289.dev">Contact me <span>↗</span></a></div></div><div className="footer-line">JUNG YE LIM — DATA ANALYTICS PORTFOLIO <span>SEOUL / KR · 2026</span></div></footer>
  </main>
}

function Project({ project, active, dataProject }: { project: Project; active: boolean; dataProject: number }) {
  return <article className={`project ${active ? 'is-active' : ''}`} id={`project-${dataProject}`} data-project={dataProject}><div className="project-meta"><span>{project.number} / 06</span><span>CASE STUDY</span></div><div className="project-main"><div><h3>{project.title}</h3><p className="project-subtitle">{project.subtitle}</p><p className="project-description">{project.description}</p><a className="project-link" href={project.githubUrl} target="_blank" rel="noreferrer">Open repository <span>↗</span></a></div><Visual project={project} /></div><div className="project-bottom"><div><span className="label">FLOW</span><div className="mini-flow">{project.flow.map((step, index) => <span key={step}>{step}{index < project.flow.length - 1 && <b>→</b>}</span>)}</div></div><div><span className="label">EVIDENCE / METRICS</span><ul>{project.metrics.map((metric) => <li key={metric}>{metric}</li>)}</ul></div><div><span className="label">TOOLS</span><ul className="muted-list">{project.tools.map((tool) => <li key={tool}>{tool}</li>)}</ul></div></div><div className="questions"><span className="label">QUESTIONS THIS STRUCTURE CAN ANSWER</span>{project.questions.map((question) => <p key={question}>{question}</p>)}</div></article>
}

function Visual({ project }: { project: Project }) {
  if (project.kind === 'districts') return <div className="visual districts"><div className="district-grid">{Array.from({ length: 25 }, (_, index) => <i className={index % 7 === 0 ? 'danger' : index % 3 === 0 ? 'warning' : ''} key={index} />)}</div><span>DEMO / REPRODUCIBLE SAMPLE<br /><b>RIR DISTRICT MATRIX</b></span></div>
  if (project.kind === 'compare') return <div className="visual compare"><div><span>LEGACY</span><b>p95 420ms</b><i /></div><div><span>REFACTOR</span><b>p95 180ms</b><i /></div><strong>SAME<br />RESULT?</strong></div>
  return <div className={`visual ${project.kind}`}><div className="visual-grid" />{project.flow.map((step, index) => <div className="visual-node" key={step} style={{ left: `${10 + index * (78 / Math.max(project.flow.length - 1, 1))}%`, top: `${35 + (index % 2) * 30}%` }}><i /><span>{step}</span></div>)}</div>
}

function ToolLine({ title, text }: { title: string; text: string }) { return <div className="tool-line"><span>{title}</span><p>{text}</p></div> }

export default App